package com.packtpub.adfguide.ch14.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 13 11:46:44 IST 2012
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {
    void updateDeparmentDetails();
}
