package com.packtpub.adfguide.ch6.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 01 14:28:38 IST 2011
// ---------------------------------------------------------------------
public interface HRAppModule extends ApplicationModule {
    void test();
}
