package com.packtpub.adfguide.ch9.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 02 07:55:20 IST 2012
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {
    String testAction(String arg);

    boolean hasMinumumEmployees();
}
