package comp.packtpub.adfguide.ch9.model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 15 08:22:57 IST 2012
// ---------------------------------------------------------------------
public interface HRAppModule extends ApplicationModule {
    boolean hastEmployeesForDepartment(Integer departmentId);
}
