package com.packtpub.adfguide.ch7.model.view.client;

import com.packtpub.adfguide.ch7.model.view.common.DepartmentVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 28 15:11:09 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentVOClient extends ViewUsageImpl implements DepartmentVO {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentVOClient() {
    }

    public void findAnUpdateDept(Integer deptId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"findAnUpdateDept",new String [] {"java.lang.Integer"},new Object[] {deptId});
        return;
    }
}
