package comp.packtpub.adfguide.ch9.model.services;

import comp.packtpub.adfguide.ch9.model.services.common.HRAppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 15 08:21:14 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRAppModuleImpl extends ApplicationModuleImpl implements HRAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRAppModuleImpl() {
    }

    /**
     * Container's getter for Departments.
     * @return Departments
     */
    public ViewObjectImpl getDepartments() {
        return (ViewObjectImpl)findViewObject("Departments");
    }

    /**
     * Container's getter for Employees.
     * @return Employees
     */
    public ViewObjectImpl getEmployees() {
        return (ViewObjectImpl)findViewObject("Employees");
    }

    public boolean hastEmployeesForDepartment(Integer departmentId) {
        ViewObjectImpl employeeVO = getEmployees();
        employeeVO.ensureVariableManager().setVariableValue("bindVarDepartmentId", departmentId);
        employeeVO.executeQuery();
        return employeeVO.getEstimatedRowCount() > 0 ? true : false;
    }
}
