package com.packtpub.adfguide.ch2.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 18 11:07:58 IST 2012
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {
    void updateDepartmentName(Integer departmentId, String departmentName);
}
