package com.packtpub.adfguide.ch9.model.service;

import com.packtpub.adfguide.ch9.model.service.common.HRServiceAppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 21 15:29:03 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleImpl extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleImpl() {
    }

    /**
     * Container's getter for Departments.
     * @return Departments
     */
    public ViewObjectImpl getDepartments() {
        return (ViewObjectImpl)findViewObject("Departments");
    }

    /**
     * Container's getter for Employees.
     * @return Employees
     */
    public ViewObjectImpl getEmployees() {
        return (ViewObjectImpl)findViewObject("Employees");
    }

    /**
     * Container's getter for EmployeesForDepartment.
     * @return EmployeesForDepartment
     */
    public ViewObjectImpl getEmployeesForDepartment() {
        return (ViewObjectImpl)findViewObject("EmployeesForDepartment");
    }

    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink1");
    }
    public String validateDepartment(){
        
        return "continue";
    }
    public String testAction(String arg){
        
        return "continue";
    }

    /**
     * Container's getter for LocationVO1.
     * @return LocationVO1
     */
    public ViewObjectImpl getLocations() {
        return (ViewObjectImpl)findViewObject("Locations");
    }
    
    public boolean hasMinumumEmployees(){
        System.out.println( "hasMinumumEmployees - " +getEmployeesForDepartment().getRowCount() );
        if(getEmployeesForDepartment().getRowCount()>5){
            return true;
        }else{
            return false;
        }
    }
}
