package com.packtpub.adfguide.ch3.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 01 12:11:33 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentEODefImpl() {
    }
}
