package com.packtpub.adfguide.ch3.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 01 22:27:48 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentEOCollImpl() {
    }
}
