package com.packtpub.adfguide.ch9.model.service.client;

import com.packtpub.adfguide.ch9.model.service.common.HRServiceAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 02 07:55:20 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleClient extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleClient() {
    }

    public boolean hasMinumumEmployees() {
        Object _ret = this.riInvokeExportedMethod(this,"hasMinumumEmployees",null,null);
        return ((Boolean)_ret).booleanValue();
    }

    public String testAction(String arg) {
        Object _ret = this.riInvokeExportedMethod(this,"testAction",new String [] {"java.lang.String"},new Object[] {arg});
        return (String)_ret;
    }
}
