package comp.packtpub.adfguide.ch9.model.services.client;

import comp.packtpub.adfguide.ch9.model.services.common.HRAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 15 08:22:57 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRAppModuleClient extends ApplicationModuleImpl implements HRAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRAppModuleClient() {
    }

    public boolean hastEmployeesForDepartment(Integer departmentId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"hastEmployeesForDepartment",new String [] {"java.lang.Integer"},new Object[] {departmentId});
        return ((Boolean)_ret).booleanValue();
    }
}
