package com.packtpub.adfguide.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 02 10:36:44 IST 2012
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {
    void buildDynamicDeptViewCompAndAddtoAM();

    void createCompositeDeptEmpVO();

    void nestAMIfRequiredAndInvokeMethod();
}
