package com.packtpub.adfguide.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 05 14:47:52 IST 2012
// ---------------------------------------------------------------------
public interface TxnAppModule extends ApplicationModule {
    void updateEmployee();
}
