package com.packtpub.adfguide.ch14.model.service.client;

import com.packtpub.adfguide.ch14.model.service.common.HRServiceAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 13 11:46:44 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleClient extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleClient() {
    }

    public void updateDeparmentDetails() {
        Object _ret = this.riInvokeExportedMethod(this,"updateDeparmentDetails",null,null);
        return;
    }
}
