package com.packtpub.adfguide.ch4.model.service.client;

import com.packtpub.adfguide.ch4.model.service.common.HRServiceAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 28 12:39:24 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleClient extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleClient() {
    }

    public void test() {
        Object _ret = this.riInvokeExportedMethod(this,"test",null,null);
        return;
    }
}
