package com.packtpub.adfguide.ch5.model.service.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.generic.GenericClob;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 04 17:16:25 IST 2011
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {
    void createCompositeDeptEmpVO();

    void saveUploadedFile(ClobDomain content, String filename);

    void findDepartmentsForDepartmnetNames(String[] deptNamesArray);

    void executeDepermentVO();

    void findDepartmentsForDepartmnetNamesUsingVC(String[] deptNamesArray);

    void buildDynamicDeptViewCompAndAddtoAM();
}
