package com.packtpub.adfguide.ch2.model.service.client;

import com.packtpub.adfguide.ch2.model.service.common.HRServiceAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 18 11:07:58 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleClient extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleClient() {
    }

    public void updateDepartmentName(Integer departmentId, String departmentName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateDepartmentName",new String [] {"java.lang.Integer","java.lang.String"},new Object[] {departmentId, departmentName});
        return;
    }
}
