package com.packtpub.adfguide.ch7.model.service;


import com.packtpub.adfguide.ch7.model.service.common.HRServiceAppModule;

import com.packtpub.adfguide.ch7.model.view.DepartmentVOImpl;

import java.util.ArrayList;

import java.util.List;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 16 12:54:48 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleImpl extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleImpl() {
    }

    /**
     * Container's getter for Departments.
     * @return Departments
     */
    public DepartmentVOImpl getDepartments() {
        return (DepartmentVOImpl)findViewObject("Departments");
    }

    /**
     * Container's getter for Employees.
     * @return Employees
     */
    public ViewObjectImpl getEmployees() {
        return (ViewObjectImpl)findViewObject("Employees");
    }

    /**
     * Container's getter for EmployeesForDepartment.
     * @return EmployeesForDepartment
     */
    public ViewObjectImpl getEmployeesForDepartment() {
        return (ViewObjectImpl)findViewObject("EmployeesForDepartment");
    }

    public Row updateDepartmentDeatils(Row departmentRow){
        System.out.println("------- updateDepartmentDeatils called -------" +departmentRow.getAttribute(1));
        return departmentRow;
    }


    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink1");
    }

   

    /**
     * Container's getter for EmpDeptFkLink2.
     * @return EmpDeptFkLink2
     */
    public ViewLinkImpl getEmpDeptFkLink2() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink2");
    }
    /**
     * A method defined in application module to find employee
     * list by city code
     * @param city
     * @return
     */
    public List findEmployeeNamesByCity(String city){
        return null;
    }
    /**
     * A method defined in application module to find employee name
     * by city code
     * @return
     */
    public String findEmployeeNameById(Integer id){
        return null;
    }
}
