package com.packtpub.adfguide.model.client;

import com.packtpub.adfguide.model.common.HRServiceAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 02 10:36:44 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleClient extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleClient() {
    }


    public void buildDynamicDeptViewCompAndAddtoAM() {
        Object _ret = this.riInvokeExportedMethod(this,"buildDynamicDeptViewCompAndAddtoAM",null,null);
        return;
    }

    public void createCompositeDeptEmpVO() {
        Object _ret = this.riInvokeExportedMethod(this,"createCompositeDeptEmpVO",null,null);
        return;
    }

    public void nestAMIfRequiredAndInvokeMethod() {
        Object _ret = this.riInvokeExportedMethod(this,"nestAMIfRequiredAndInvokeMethod",null,null);
        return;
    }
}
