DROP SEQUENCE file_storage_seq;
DROP TABLE file_storage;
CREATE TABLE file_storage(
  FILE_ID NUMBER PRIMARY KEY,
  FILE_NAME VARCHAR2(80),
  FILE_CONTENT CLOB,
  CREATED_ON DATE);
CREATE SEQUENCE file_storage_seq;
CREATE TRIGGER assign_file_id BEFORE INSERT ON file_storage FOR EACH ROW
BEGIN
  SELECT file_storage_seq.NEXTVAL INTO :NEW.FILE_ID FROM dual;
END;
CREATE OR REPLACE TYPE  "CHARTABLETYPE"  AS TABLE OF VARCHAR2(4000);
CREATE TABLE "REGIONAL_OFFICE"
  (
    "BRANCH_ID"   NUMBER PRIMARY KEY,
    "BRANCH_NAME" VARCHAR2(20 BYTE),
    "REGION_ID"   NUMBER,
    "COUNTRY_ID"  CHAR(2 BYTE)
  );
 
DROP TABLE CONTACT;
DROP TYPE ADDRESS_DETAIL;
CREATE OR REPLACE TYPE ADDRESS_DETAIL AS OBJECT ( CITY VARCHAR2(100), COUNTRY VARCHAR2(100));
.
/
CREATE TABLE CONTACT(
  CONTACT_ID NUMBER PRIMARY KEY,
  CONTACT_NAME VARCHAR2(100),
  ADDRESS ADDRESS_DETAIL,
  DESCRIPTION VARCHAR2(200)
);
INSERT INTO CONTACT VALUES(1001,'Jobinesh',ADDRESS_DETAIL('Bangalore','India'),'Primary Contact');
COMMIT;