package com.packtpub.adfguide.ch11.model.service.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 14 18:20:15 IST 2012
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {


    void methodThrowingError();

    void throwAttrValExceptionProgrammatically();

    void throwRowValExceptionProgrammatically();

    void throwTxnValExceptionProgrammatically();


    void throwAttrSetValExceptionProgrammatically();

    void throwValidationExceptionsProgrammatically();

    void validateDepartmentName(Row deptRow);
}
