package com.packtpub.adfguide.ch11.model.service;

import oracle.jbo.common.PropertiesBundleDef;
import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 14 18:22:38 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleDefImpl extends ApplicationModuleDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleDefImpl() {
    }

    @Override
    protected void finishedLoading() {
        super.finishedLoading();
        PropertiesBundleDef propBundleDef = new PropertiesBundleDef(this);
        propBundleDef.setPropertiesFile("com.packtpub.adfguide.ch11.model.HRDataModelBundle");
        setResourceBundleDef(propBundleDef);
    }
}
