package com.packtpub.adfguide.ch4.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 28 12:39:24 IST 2011
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {
    void test();
}
