package com.packtpub.adfguide.ch5.model.view;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 03 11:13:33 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeVOImpl() {
    }
    public void prepareRowSetForQuery(ViewRowSetImpl vrs) {
        if (vrs.isDefaultRowSet()) {
            vrs.setNamedWhereClauseParam("bindVarDeptId", 10);

        }
    }

    /**
     * Returns the bind variable value for bindVarDeptId.
     * @return bind variable value for bindVarDeptId
     */
    public Integer getbindVarDeptId() {
        return (Integer)getNamedWhereClauseParam("bindVarDeptId");
    }

    /**
     * Sets <code>value</code> for bind variable bindVarDeptId.
     * @param value value to bind as bindVarDeptId
     */
    public void setbindVarDeptId(Integer value) {
        setNamedWhereClauseParam("bindVarDeptId", value);
    }
}
