package com.packtpub.adfguide.ch5.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 06 12:53:56 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FileStorageVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FileStorageVOImpl() {
    }
}
