package com.packtpub.adfguide.ch11.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 15 12:13:35 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentEOCollImpl() {
    }
}
