package com.packtpub.adfguide.ch4.model.entity;

import oracle.jbo.Key;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 26 13:52:11 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SalesEmployeeExEOImpl extends ExecutiveEmployeeExEOImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SalesEmployeeExEOImpl() {
    }

    /**
     * @param employeeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer employeeId) {
        return new Key(new Object[]{employeeId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.packtpub.adfguide.ch4.model.entity.SalesEmployeeExEO");
    }


    public void processRow() {
        System.out.println("- SalesEmployeeExEOImpl::processRow -");

    }
}
