package com.packtpub.adfguide.ch2.model.service;


import com.packtpub.adfguide.ch2.model.service.common.HRServiceAppModule;
import com.packtpub.adfguide.ch2.model.view.DepartmentVORowImpl;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 13 18:38:40 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleImpl extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleImpl() {
    }

    /**
     * Container's getter for DepartmentVO1.
     * @return DepartmentVO1
     */
    public ViewObjectImpl getDepartments() {
        return (ViewObjectImpl)findViewObject("Departments");
    }


    /**
     * Container's getter for EmployeeVO3.
     * @return EmployeeVO3
     */
    public ViewObjectImpl getEmployeesForDepartment() {
        return (ViewObjectImpl)findViewObject("EmployeesForDepartment");
    }


    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink1");
    }
    /**
     * Acsutom method to update departement name
     * @param departmentId
     * @param departmentName
     */
    public void updateDepartmentName(Integer departmentId, String departmentName) {
        Key key = new Key(new Object[] { departmentId });
        DepartmentVORowImpl deptRow =(DepartmentVORowImpl) getDepartments().getRow(key);
        deptRow.setDepartmentName(departmentName);
        getTransaction().commit();
    }
}
