package com.packtpub.adfguide.ch7.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 28 15:11:09 IST 2011
// ---------------------------------------------------------------------
public interface DepartmentVO extends ViewObject {
    void findAnUpdateDept(Integer deptId);
}
