package com.packtpub.adfguide.ch7.model.view;

import com.packtpub.adfguide.ch7.model.view.common.DepartmentVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 26 20:31:56 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentVOImpl extends ViewObjectImpl implements DepartmentVO {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentVOImpl() {
       
    }

    /**
     * Returns the bind variable value for bindVarDeptId.
     * @return bind variable value for bindVarDeptId
     */
    public Integer getbindVarDeptId() {
        return (Integer)getNamedWhereClauseParam("bindVarDeptId");
    }

    /**
     * Sets <code>value</code> for bind variable bindVarDeptId.
     * @param value value to bind as bindVarDeptId
     */
    public void setbindVarDeptId(Integer value) {
        setNamedWhereClauseParam("bindVarDeptId", value);
    }
    public void findAnUpdateDept(Integer deptId){
        
    }
}
