package com.packtpub.adfguide.ch3.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 29 11:03:21 IST 2011
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {
    void test();


    void commit();

    void findDepeartmentAndEmployees(Integer deptId);
}
