package com.packtpub.adfguide.ch4.model.view;

import oracle.jbo.NameValuePairs;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 26 13:55:08 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarketingEmployeeListVOImpl extends MarketingEmployeeGenericVOImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MarketingEmployeeListVOImpl() {
    }

    public MarketingEmployeeListVORowImpl createSalesEmployee() {
        NameValuePairs nvp = new NameValuePairs();
        nvp.setAttribute("DepartmentId", "90");
        return (MarketingEmployeeListVORowImpl)createAndInitRow(nvp);
    }

    public MarketingEmployeeListVORowImpl createExecutiveEmployee() {
        NameValuePairs nvp = new NameValuePairs();
        nvp.setAttribute("DepartmentId", "80");
        return (MarketingEmployeeListVORowImpl)createAndInitRow(nvp);
    }

    public MarketingEmployeeListVORowImpl createGenericMarketingEmployee() {
        NameValuePairs nvp = new NameValuePairs();
        nvp.setAttribute("DepartmentId", "20");
        return (MarketingEmployeeListVORowImpl)createAndInitRow(nvp);
    }
}
