package com.packtpub.adfguide.ch4.model.view;

import com.packtpub.adfguide.ch4.model.entity.MarketingEmployeeGenericEOImpl;

import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 26 14:09:07 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarketingEmployeeGenericVORowImpl extends ViewRowImpl {


    public static final int ENTITY_MARKETINGEMPLOYEEGENERICEO = 0;

    /**
     * This is the default constructor (do not remove).
     */
    public MarketingEmployeeGenericVORowImpl() {
    }

    /**
     * Gets MarketingEmployeeGenericEO entity object.
     * @return the MarketingEmployeeGenericEO
     */
    public MarketingEmployeeGenericEOImpl getMarketingEmployeeGenericEO() {
        return (MarketingEmployeeGenericEOImpl)getEntity(ENTITY_MARKETINGEMPLOYEEGENERICEO);
    }

    public void processRow() {
        System.out.println("+MarketingEmployeeGenericVORowImpl::processRow+");
        getMarketingEmployeeGenericEO().processRow();
    }
}
