package com.packtpub.adfguide.ch4.model.view;

import com.packtpub.adfguide.ch4.model.entity.MarketingEmployeeGenericEOImpl;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 26 13:55:08 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarketingEmployeeListVORowImpl extends MarketingEmployeeGenericVORowImpl {

    public static final int MAXUSAGECONST = 1;

    /**
     * This is the default constructor (do not remove).
     */
    public MarketingEmployeeListVORowImpl() {
    }
    public void processRow(){
           System.out.println("+MarketingEmployeeListVORowImpl::processRow+");
           getMarketingEmployeeGenericEO().processRow();
       }
}
