package com.packtpub.adfguide.ch4.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 26 14:09:07 IST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MarketingEmployeeGenericVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MarketingEmployeeGenericVOImpl() {
    }
}
